---
- hosts: all
  vars_files:
  - ./vars.yml

  tasks:

    - name: Install Python Pycurl
      apt:
        name: python-pycurl
        state: latest  

    - name: Install the Nginx Repository 
      apt_repository:
        repo: "ppa:nginx/stable"
        state: present

    - name: Update the Repositories 
      apt: 
        update_cache: yes
     
    - name: Install Nginx
      apt:
        name: nginx 
        state: latest
     
    - name: Write the modified nginx.conf
      template:
        src: "nginx.conf.j2" 
        dest: "/etc/nginx/nginx.conf"
      notify:
        - Restart Nginx  

    - name: Delete the default unnecessary files
      file:
        dest: "{{ item }}"
        state: absent
      with_items:
       - "/etc/nginx/sites-enabled/default"
       - "/var/www/html/index.nginx-debian.html"
      notify:
        - Restart Nginx

    - name: Apache | add Nginx iptable rule
      command: /sbin/iptables -I INPUT 1 -p tcp --dport http -j ACCEPT -m comment --comment "Nginx"
      command: /sbin/iptables -I INPUT 1 -p tcp --dport https -j ACCEPT -m comment --comment "Nginx"

    - name: save iptables
      command: iptables-save

    - name: restart iptables
      service: name=ufw state=restarted

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
